use_frameworks!

platform :ios, '8.0'

target 'XyzCustomKeyBoard_Example' do
  pod 'XyzCustomKeyBoard', :path => '../'

  target 'XyzCustomKeyBoard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
